//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package hu.todo.adapter;

import android.content.Context;

public final class TitleNavigationAdapter_
    extends TitleNavigationAdapter
{

    private Context context_;

    private TitleNavigationAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static TitleNavigationAdapter_ getInstance_(Context context) {
        return new TitleNavigationAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
