//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package hu.todo.adapter;

import android.content.Context;

public final class TodoAdapter_
    extends TodoAdapter
{

    private Context context_;

    private TodoAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static TodoAdapter_ getInstance_(Context context) {
        return new TodoAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
