//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package hu.todo.rest;

import android.content.Context;

public final class MyErrorHandler_
    extends MyErrorHandler
{

    private Context context_;

    private MyErrorHandler_(Context context) {
        context_ = context;
        init_();
    }

    public static MyErrorHandler_ getInstance_(Context context) {
        return new MyErrorHandler_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
