//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package hu.todo.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.MenuItem;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.MultiAutoCompleteTextView;
import android.widget.TextView;
import hu.todo.R.layout;
import hu.todo.entity.Task;
import hu.todo.rest.TaskRestInterface_;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class TaskActivity_
    extends TaskActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String TASK_EXTRA = "task";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_task);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        taskManager = new TaskRestInterface_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static TaskActivity_.IntentBuilder_ intent(Context context) {
        return new TaskActivity_.IntentBuilder_(context);
    }

    public static TaskActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new TaskActivity_.IntentBuilder_(fragment);
    }

    public static TaskActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new TaskActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        updated = ((TextView) hasViews.findViewById(hu.todo.R.id.updated));
        title = ((TextView) hasViews.findViewById(hu.todo.R.id.title));
        createdPicker = ((EditText) hasViews.findViewById(hu.todo.R.id.createdPicker));
        updatedPicker = ((EditText) hasViews.findViewById(hu.todo.R.id.updatedPicker));
        datePicker = ((EditText) hasViews.findViewById(hu.todo.R.id.datePicker));
        date = ((TextView) hasViews.findViewById(hu.todo.R.id.date));
        btnCreate = ((Button) hasViews.findViewById(hu.todo.R.id.btnCreate));
        user = ((MultiAutoCompleteTextView) hasViews.findViewById(hu.todo.R.id.user));
        created = ((TextView) hasViews.findViewById(hu.todo.R.id.created));
        description = ((EditText) hasViews.findViewById(hu.todo.R.id.description));
        {
            View view = hasViews.findViewById(hu.todo.R.id.btnCreate);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        TaskActivity_.this.plusButtonWasClicked();
                    }

                }
                );
            }
        }
        afterViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(TASK_EXTRA)) {
                task = extras_.getParcelable(TASK_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean handled = super.onOptionsItemSelected(item);
        if (handled) {
            return true;
        }
        int itemId_ = item.getItemId();
        if (itemId_ == android.R.id.home) {
            navigateBackOnHomePress(item);
            return true;
        }
        return false;
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, TaskActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, TaskActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, TaskActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public TaskActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public TaskActivity_.IntentBuilder_ task(Task task) {
            intent_.putExtra(TASK_EXTRA, task);
            return this;
        }

    }

}
