//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package hu.todo.rest.java.util;

import java.util.ArrayList;
import hu.todo.entity.User;

public class List_User
    extends ArrayList<User>
{


}
